// Builds every token output from the DTCG sources in tokens/.
//
//   build/tokens.css                  CSS variables: base, light (default), dark
//   build/tokens.json                 flat list + per-theme values (used by the reference site)
//   unity/MyGamedevToolsUI/Styles/Tokens.uss  USS variables for runtime UI (dark default, light class)
//   packages/docusaurus-theme/src/tokens.css  the same CSS, bundled into the theme tarball
//   packages/docusaurus-theme/static  logo files copied from assets/logo
import { cp, mkdir, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensDist = join(root, 'build');
const ussDir = join(root, 'unity/MyGamedevToolsUI/Styles');
const PREFIX = 'mgt';
const HEADER = 'Generated by scripts/build-tokens.mjs from tokens/. Do not edit by hand.';

async function resolve(source) {
  const sd = new StyleDictionary({
    source: source.map((s) => join(root, s)),
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        prefix: PREFIX,
        transforms: ['name/kebab', 'fontFamily/css', 'cubicBezier/css'],
      },
    },
  });
  const { allTokens } = await sd.getPlatformTokens('css');
  return allTokens.map((t) => ({
    name: `--${t.name}`,
    path: t.path,
    type: t.$type ?? t.type,
    value: t.$value ?? t.value,
    description: t.$description ?? t.description ?? '',
    file: relative(root, t.filePath).split(sep).join('/'),
  }));
}

const fromDir = (tokens, dir) => tokens.filter((t) => t.file.startsWith(dir));
const declarations = (tokens, indent = '  ') =>
  tokens.map((t) => `${indent}${t.name}: ${t.value};`).join('\n');

const light = await resolve(['tokens/base/**/*.json', 'tokens/themes/light.json']);
const dark = await resolve(['tokens/base/**/*.json', 'tokens/themes/dark.json']);
const base = fromDir(light, 'tokens/base/');
const lightTheme = fromDir(light, 'tokens/themes/');
const darkTheme = fromDir(dark, 'tokens/themes/');

// CSS: light is the default; dark applies via data-theme (Docusaurus, the site) or the OS
// preference when no data-theme is set. Any element can opt into a theme with data-theme.
const css = `/* ${HEADER} */
:root {
  color-scheme: light;
${declarations(base)}
${declarations(lightTheme)}
}

[data-theme='light'] {
  color-scheme: light;
${declarations(lightTheme)}
}

[data-theme='dark'] {
  color-scheme: dark;
${declarations(darkTheme)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    color-scheme: dark;
${declarations(darkTheme, '    ')}
  }
}
`;

const darkByName = Object.fromEntries(darkTheme.map((t) => [t.name, t.value]));
const json = {
  $comment: HEADER,
  tokens: [
    ...base.map((t) => ({ ...t, theme: 'base' })),
    ...lightTheme.map((t) => ({ ...t, theme: 'semantic', light: t.value, dark: darkByName[t.name] })),
  ].map(({ file, ...t }) => t),
};

// USS for runtime UI Toolkit (sample loading screens, HUDs, menus). Unity only understands
// colors and px dimensions as variables; fonts are assets, referenced in Brand.uss. Game UI
// usually sits over a dark scene, so dark is the default and .mgt-theme-light opts into light.
const ussUsable = (t) =>
  t.type === 'color' || (t.type === 'dimension' && String(t.value).endsWith('px'));
const uss = `/* ${HEADER} */
:root,
.mgt-theme-dark {
${declarations(base.filter(ussUsable), '    ')}
${declarations(darkTheme.filter(ussUsable), '    ')}
}

.mgt-theme-light {
${declarations(lightTheme.filter(ussUsable), '    ')}
}
`;

await mkdir(tokensDist, { recursive: true });
await mkdir(ussDir, { recursive: true });
await Promise.all([
  writeFile(join(tokensDist, 'tokens.css'), css),
  writeFile(join(tokensDist, 'tokens.json'), `${JSON.stringify(json, null, 2)}\n`),
  writeFile(join(root, 'packages/docusaurus-theme/src/tokens.css'), css),
  writeFile(join(ussDir, 'Tokens.uss'), uss),
]);

// The Docusaurus theme serves the logo files from its own static directory.
const themeImg = join(root, 'packages/docusaurus-theme/static/img/mgt');
await mkdir(themeImg, { recursive: true });
await cp(join(root, 'assets/logo/svg'), themeImg, { recursive: true });
for (const file of await readdir(join(root, 'assets/logo/png'))) {
  if (/-(128|256|512)\.png$/.test(file)) await cp(join(root, 'assets/logo/png', file), join(themeImg, file));
}

console.log(
  `tokens: ${base.length} base, ${lightTheme.length} semantic (light/dark) -> build/, docusaurus theme, unity/MyGamedevToolsUI/Styles/Tokens.uss`,
);
